ALTER TABLE candidates
ADD COLUMN create_date TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN last_update_date TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE companies
ADD COLUMN create_date TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN last_update_date TIMESTAMP NOT NULL DEFAULT NOW();
